apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${RELEASE_NAME:-forms-waf}-haproxy
  namespace: ${NAMESPACE:-forms-waf}
  labels:
    app.kubernetes.io/name: forms-waf
    app.kubernetes.io/component: haproxy
spec:
  serviceName: ${RELEASE_NAME:-forms-waf}-haproxy-headless
  replicas: ${HAPROXY_REPLICAS:-3}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/name: forms-waf
      app.kubernetes.io/component: haproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: forms-waf
        app.kubernetes.io/component: haproxy
    spec:
      containers:
        - name: haproxy
          image: ${HAPROXY_IMAGE:-forms-waf/haproxy}:${HAPROXY_TAG:-latest}
          imagePullPolicy: ${IMAGE_PULL_POLICY:-IfNotPresent}
          args:
            - haproxy
            - "-f"
            - "/usr/local/etc/haproxy/haproxy.cfg"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: stats
              containerPort: 8404
              protocol: TCP
            - name: health
              containerPort: 8405
              protocol: TCP
            - name: peer
              containerPort: 10000
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_MODE
              value: "true"
          livenessProbe:
            httpGet:
              path: /health
              port: 8405
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8405
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: ${HAPROXY_CPU_LIMIT:-500m}
              memory: ${HAPROXY_MEMORY_LIMIT:-512Mi}
            requests:
              cpu: ${HAPROXY_CPU_REQUEST:-100m}
              memory: ${HAPROXY_MEMORY_REQUEST:-128Mi}
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
            - name: run
              mountPath: /var/run
      volumes:
        - name: haproxy-config
          configMap:
            name: ${RELEASE_NAME:-forms-waf}-haproxy-config
        - name: run
          emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - haproxy
                topologyKey: kubernetes.io/hostname
---
# Headless service for StatefulSet peer discovery
# publishNotReadyAddresses ensures DNS returns IPs even for unready pods,
# which is required for HAProxy peer discovery during parallel pod startup
apiVersion: v1
kind: Service
metadata:
  name: ${RELEASE_NAME:-forms-waf}-haproxy-headless
  namespace: ${NAMESPACE:-forms-waf}
  labels:
    app.kubernetes.io/name: forms-waf
    app.kubernetes.io/component: haproxy
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 8080
      targetPort: http
      name: http
    - port: 10000
      targetPort: peer
      name: peer
  selector:
    app.kubernetes.io/name: forms-waf
    app.kubernetes.io/component: haproxy
---
# Regular service
apiVersion: v1
kind: Service
metadata:
  name: ${RELEASE_NAME:-forms-waf}-haproxy
  namespace: ${NAMESPACE:-forms-waf}
  labels:
    app.kubernetes.io/name: forms-waf
    app.kubernetes.io/component: haproxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      name: http
    - port: 8404
      targetPort: stats
      name: stats
    - port: 8405
      targetPort: health
      name: health
  selector:
    app.kubernetes.io/name: forms-waf
    app.kubernetes.io/component: haproxy
