apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${RELEASE_NAME:-forms-waf}-redis
  namespace: ${NAMESPACE:-forms-waf}
  labels:
    app.kubernetes.io/name: forms-waf
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: forms-waf
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: forms-waf
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          command:
            - redis-server
            - --maxmemory
            - 256mb
            - --maxmemory-policy
            - allkeys-lru
            - --appendonly
            - "yes"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: ${REDIS_CPU_LIMIT:-250m}
              memory: ${REDIS_MEMORY_LIMIT:-256Mi}
            requests:
              cpu: ${REDIS_CPU_REQUEST:-50m}
              memory: ${REDIS_MEMORY_REQUEST:-64Mi}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ${RELEASE_NAME:-forms-waf}-redis
  namespace: ${NAMESPACE:-forms-waf}
  labels:
    app.kubernetes.io/name: forms-waf
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: forms-waf
    app.kubernetes.io/component: redis
