/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** WAF status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WafStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global thresholds */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Effective thresholds and defaults */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            thresholds: components["schemas"]["Thresholds"];
                            defaults?: Record<string, never>;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global routing */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Effective routing and defaults */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            routing: components["schemas"]["GlobalRouting"];
                            defaults?: components["schemas"]["GlobalRouting"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timing/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Form timing token configuration */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Timing configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimingTokenConfig"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slack/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Slack notification configuration */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Configuration, defaults and event availability */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            config: components["schemas"]["SlackConfig"];
                            defaults: components["schemas"]["SlackConfig"];
                            emitted_events?: string[];
                            unavailable_events?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keywords/blocked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blocked keywords */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Keyword list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            keywords: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vhosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Virtual hosts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All vhosts visible to the session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            vhosts: Record<string, never>[];
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoints */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All endpoints visible to the session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            endpoints: Record<string, never>[];
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Thresholds: {
            /** @description Score at which a request is blocked */
            spam_score_block: number;
            /** @description Score at which a request is flagged */
            spam_score_flag: number;
            hash_count_block: number;
            hash_unique_ips_block?: number;
            ip_rate_limit: number;
            ip_daily_limit: number;
            fingerprint_rate_limit?: number;
            ip_spam_score_threshold?: number;
            expose_waf_headers?: boolean;
            rate_limiting_enabled?: boolean;
        };
        GlobalRouting: {
            /** @description HTTP upstream address. Note the port; HAProxy binds 8080. */
            haproxy_upstream: string;
            haproxy_upstream_ssl?: string;
            /**
             * @description Use the SSL upstream address. There is no `haproxy_ssl` field --
             *     the admin UI bound a toggle to that name and it silently did nothing.
             */
            upstream_ssl?: boolean;
            haproxy_timeout?: number;
        };
        TimingTokenConfig: {
            enabled: boolean;
            cookie_name: string;
            cookie_ttl?: number;
            /** @description Seconds below which a submission is blocked. NOT min_time_seconds. */
            min_time_block: number;
            /** @description Seconds below which a submission is flagged. NOT suspicious_time_seconds. */
            min_time_flag: number;
            /** @description Added when no timing cookie is present. NOT no_cookie_score. */
            score_no_cookie: number;
            /** @description NOT too_fast_score. */
            score_too_fast: number;
            /** @description NOT suspicious_score. */
            score_suspicious: number;
            path_match_mode?: string;
            apply_to_methods?: string[];
            set_on_methods?: string[];
        };
        SlackConfig: {
            enabled: boolean;
            /** @description Masked as "***" on read; submit the mask unchanged to keep the stored value. */
            webhook_url?: string;
            webhook_url_set?: boolean;
            channel?: string;
            update_interval: number;
            resolution_threshold: number;
            events: string[];
            mention_users?: string[];
            mention_on_high_severity?: boolean;
            severity_thresholds?: {
                high_event_count?: number;
                high_event_rate?: number;
            };
        };
        WafStatus: {
            redis_host?: string;
            redis_port?: number;
            redis_connected: boolean;
            sync_interval?: number;
            blocked_hashes_count: number;
            whitelisted_ips_count: number;
            endpoints_count: number;
            vhosts_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
